# Generated by Django 5.2.10 on 2026-04-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetOtchet',
            fields=[
                ('id_dataset', models.AutoField(primary_key=True, serialize=False)),
                ('familia', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('otchestvo', models.TextField(blank=True, null=True)),
                ('module', models.TextField(blank=True, null=True)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('kurs', models.IntegerField(blank=True, null=True)),
                ('group', models.TextField(blank=True, null=True)),
                ('date_begin', models.TextField(blank=True, null=True)),
                ('date_finish', models.TextField(blank=True, null=True)),
                ('head1', models.TextField(blank=True, null=True)),
                ('head2', models.TextField(blank=True, null=True)),
                ('ruc_pract', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataset_otchet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PracType',
            fields=[
                ('id_prac_type', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'prac_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('title', 'Титульный лист'), ('assignment', 'Задание'), ('diary', 'Дневник')], max_length=20, unique=True, verbose_name='Тип документа')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('template_file', models.FileField(upload_to='templates/', verbose_name='Файл шаблона')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
            },
        ),
    ]
